<?php
/**
 * VAMS Database Configuration
 * Auto-generated by installer on 2026-08-09 08:18:39
 */

define('DB_HOST', 'localhost');
define('DB_PORT', '3306');
define('DB_NAME', 'visitor_test');
define('DB_USER', 'root');
define('DB_PASS', '');

/**
 * Get PDO Database Connection
 * 
 * @return PDO
 * @throws PDOException
 */
function getDbConnection() {
    static $pdo = null;
    
    if ($pdo === null) {
        try {
            $dsn = 'mysql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=utf8mb4';
            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ];
            
            $pdo = new PDO($dsn, DB_USER, DB_PASS, $options);
        } catch (PDOException $e) {
            error_log('Database connection failed: ' . $e->getMessage());
            throw $e;
        }
    }
    
    return $pdo;
}

/**
 * Execute a SELECT query and fetch all results
 * 
 * @param PDO $pdo
 * @param string $sql
 * @param array $params
 * @return array
 */
function fetchAll($pdo, $sql, $params = []) {
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    return $stmt->fetchAll();
}

/**
 * Execute a SELECT query and fetch one result
 * 
 * @param PDO $pdo
 * @param string $sql
 * @param array $params
 * @return array|false
 */
function fetchOne($pdo, $sql, $params = []) {
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    return $stmt->fetch();
}

/**
 * Execute an INSERT query and return last insert ID
 * 
 * @param PDO $pdo
 * @param string $sql
 * @param array $params
 * @return int
 */
function insertRecord($pdo, $sql, $params = []) {
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    return $pdo->lastInsertId();
}

/**
 * Execute an UPDATE or DELETE query and return affected rows
 * 
 * @param PDO $pdo
 * @param string $sql
 * @param array $params
 * @return int
 */
function updateRecord($pdo, $sql, $params = []) {
    $stmt = $pdo->prepare($sql);
    $stmt->execute($params);
    return $stmt->rowCount();
}
