<?php
/**
 * VAMS Installer - Process Installation (AJAX Endpoint)
 */

// Load configuration for session name
require_once __DIR__ . '/../config/constants.php';

// Increase execution time for large SQL imports
set_time_limit(300);

if (session_status() === PHP_SESSION_NONE) {
    session_name(SESSION_NAME);
    session_start();
}

header('Content-Type: application/json');

// Check if already installed
$lockFile = __DIR__ . '/../config/installed.lock';
if (file_exists($lockFile)) {
    echo json_encode(['success' => false, 'message' => 'System is already installed']);
    exit;
}

// Get installer data from session
$dbHost = $_SESSION['installer']['db_host'] ?? '';
$dbPort = $_SESSION['installer']['db_port'] ?? '';
$dbName = $_SESSION['installer']['db_name'] ?? '';
$dbUsername = $_SESSION['installer']['db_username'] ?? '';
$dbPassword = $_SESSION['installer']['db_password'] ?? '';
$appName = $_SESSION['installer']['app_name'] ?? '';
$adminName = $_SESSION['installer']['admin_name'] ?? '';
$adminEmail = $_SESSION['installer']['admin_email'] ?? '';
$adminPassword = $_SESSION['installer']['admin_password'] ?? '';
$dbFilePath = $_SESSION['installer']['db_file_path'] ?? '';

// Validate required data
if (empty($dbHost) || empty($dbPort) || empty($dbName) || empty($dbUsername) || 
    empty($appName) || empty($adminName) || empty($adminEmail) || empty($adminPassword)) {
    error_log('Installer: Missing required installation data');
    echo json_encode(['success' => false, 'message' => 'Missing required installation data']);
    exit;
}

if (empty($dbFilePath)) {
    echo json_encode(['success' => false, 'message' => 'Database file path not found in session. Please start over from Step 2.']);
    exit;
}

if (!file_exists($dbFilePath)) {
    error_log('Installer: Database file does not exist at path: ' . $dbFilePath);
    echo json_encode(['success' => false, 'message' => 'Database file not found at: ' . $dbFilePath . '. Please upload it again in Step 2.']);
    exit;
}

try {
    // Step 1: Connect to MySQL server (without database name)
    $dsn = "mysql:host={$dbHost};port={$dbPort};charset=utf8mb4";
    $options = [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ];
    $pdo = new PDO($dsn, $dbUsername, $dbPassword, $options);
    
    // Step 2: Create database if not exists
    $pdo->exec("CREATE DATABASE IF NOT EXISTS `{$dbName}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
    
    // Step 3: Reconnect with database name and enable multi-statements
    $dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
    $options = [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::MYSQL_ATTR_MULTI_STATEMENTS => true, // Enable for multi-statement SQL import
    ];
    $pdo = new PDO($dsn, $dbUsername, $dbPassword, $options);
    
    // Step 4: Read and execute SQL file
    $sqlContent = file_get_contents($dbFilePath);
    if ($sqlContent === false) {
        throw new Exception('Could not read SQL file');
    }
    
    // Execute the full SQL content
    $pdo->exec($sqlContent);
    
    // Step 5: Replace seed admin account
    // Get Admin role ID
    $stmt = $pdo->prepare("SELECT id FROM roles WHERE role_name = 'Admin' LIMIT 1");
    $stmt->execute();
    $adminRole = $stmt->fetch(PDO::FETCH_ASSOC);
    
    if (!$adminRole) {
        throw new Exception('Admin role not found in database');
    }
    
    $adminRoleId = $adminRole['id'];
    
    // Check if seed admin exists (admin@vams.com)
    $stmt = $pdo->prepare("SELECT id FROM users WHERE email = 'admin@vams.com' LIMIT 1");
    $stmt->execute();
    $seedAdmin = $stmt->fetch(PDO::FETCH_ASSOC);
    
    // Hash the new password
    $passwordHash = password_hash($adminPassword, PASSWORD_DEFAULT);
    
    if ($seedAdmin) {
        // Update existing seed admin
        $stmt = $pdo->prepare("UPDATE users SET full_name = ?, email = ?, password_hash = ?, status = 'active', is_deleted = 0 WHERE email = 'admin@vams.com'");
        $stmt->execute([$adminName, $adminEmail, $passwordHash]);
    } else {
        // Insert new admin user
        $stmt = $pdo->prepare("INSERT INTO users (employee_id, full_name, email, password_hash, role_id, status, is_deleted, created_at, updated_at) VALUES (?, ?, ?, ?, ?, 'active', 0, NOW(), NOW())");
        $stmt->execute(['ADMIN001', $adminName, $adminEmail, $passwordHash, $adminRoleId]);
    }
    
    // Step 6: Update site_settings app_name
    $stmt = $pdo->prepare("INSERT INTO site_settings (setting_key, setting_value) VALUES ('app_name', ?) ON DUPLICATE KEY UPDATE setting_value = ?");
    $stmt->execute([$appName, $appName]);
    
    // Step 7: Generate /config/db.php
    $dbPhpContent = "<?php
/**
 * VAMS Database Configuration
 * Auto-generated by installer on " . date('Y-m-d H:i:s') . "
 */

define('DB_HOST', '{$dbHost}');
define('DB_PORT', '{$dbPort}');
define('DB_NAME', '{$dbName}');
define('DB_USER', '{$dbUsername}');
define('DB_PASS', '{$dbPassword}');

/**
 * Get PDO Database Connection
 * 
 * @return PDO
 * @throws PDOException
 */
function getDbConnection() {
    static \$pdo = null;
    
    if (\$pdo === null) {
        try {
            \$dsn = 'mysql:host=' . DB_HOST . ';port=' . DB_PORT . ';dbname=' . DB_NAME . ';charset=utf8mb4';
            \$options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ];
            
            \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, \$options);
        } catch (PDOException \$e) {
            error_log('Database connection failed: ' . \$e->getMessage());
            throw \$e;
        }
    }
    
    return \$pdo;
}

/**
 * Execute a SELECT query and fetch all results
 * 
 * @param PDO \$pdo
 * @param string \$sql
 * @param array \$params
 * @return array
 */
function fetchAll(\$pdo, \$sql, \$params = []) {
    \$stmt = \$pdo->prepare(\$sql);
    \$stmt->execute(\$params);
    return \$stmt->fetchAll();
}

/**
 * Execute a SELECT query and fetch one result
 * 
 * @param PDO \$pdo
 * @param string \$sql
 * @param array \$params
 * @return array|false
 */
function fetchOne(\$pdo, \$sql, \$params = []) {
    \$stmt = \$pdo->prepare(\$sql);
    \$stmt->execute(\$params);
    return \$stmt->fetch();
}

/**
 * Execute an INSERT query and return last insert ID
 * 
 * @param PDO \$pdo
 * @param string \$sql
 * @param array \$params
 * @return int
 */
function insertRecord(\$pdo, \$sql, \$params = []) {
    \$stmt = \$pdo->prepare(\$sql);
    \$stmt->execute(\$params);
    return \$pdo->lastInsertId();
}

/**
 * Execute an UPDATE or DELETE query and return affected rows
 * 
 * @param PDO \$pdo
 * @param string \$sql
 * @param array \$params
 * @return int
 */
function updateRecord(\$pdo, \$sql, \$params = []) {
    \$stmt = \$pdo->prepare(\$sql);
    \$stmt->execute(\$params);
    return \$stmt->rowCount();
}
";
    
    $dbPhpPath = __DIR__ . '/../config/db.php';
    file_put_contents($dbPhpPath, $dbPhpContent);
    
    // Step 8: Delete temporary uploaded file
    if (file_exists($dbFilePath)) {
        unlink($dbFilePath);
    }
    
    // Step 9: Create lock file
    $lockContent = date('Y-m-d H:i:s') . ' - Installed successfully';
    file_put_contents($lockFile, $lockContent);
    
    // Step 10: Clear installer session data
    unset($_SESSION['installer']);
    
    // Success
    echo json_encode([
        'success' => true,
        'message' => 'Installation completed successfully',
        'admin_email' => $adminEmail
    ]);
    
} catch (PDOException $e) {
    // Database error - show actual error for installer context
    echo json_encode([
        'success' => false,
        'message' => 'Database error: ' . $e->getMessage()
    ]);
} catch (Exception $e) {
    // General error
    echo json_encode([
        'success' => false,
        'message' => $e->getMessage()
    ]);
}
